apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{.Release.Name}}-configmap
data:
  myvalue: "Sample config Map"
  costcode:  {{ .Values.costcode }}
  projectCode: {{ upper .Values.projectCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  {{- if eq .Values.infra.region "us-e" }}
  ha: "true"
  {{- end }}
  pipeline: {{ .Values.projectCode | upper | quote }} 
  now: {{ now | date "2006-01-02" | quote }}
  contact: {{ .Values.contact | default "1-800-123-0000" | quote }}
