#{{- define "mychart.systemlabels"}}
# labels:
#    drive: ssd
#    machine: frontdrive
#    rack: 4c
#    vcard: 8g
#{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configmap
  {{- template "mychart.systemlabels" . }}
data:
  myvalue: "Sample config Map"
  orgdomain: {{ .Values.global.orgdomain }}

